import { createFileRoute } from "@tanstack/react-router";
import { InfoPage, InfoList } from "@/components/InfoPage";
import { buildSeoHead } from "@/lib/seo";

export const Route = createFileRoute("/disclaimer")({
  head: () =>
    buildSeoHead({
      title: "Disclaimer — TAIPOQ",
      description:
        "Important disclaimer: TAIPOQ is an independent practice platform, not a government website.",
      path: "/disclaimer",
    }),
  component: Disclaimer,
});

const POINTS = [
  "TAIPOQ is not an official government recruitment website.",
  "TAIPOQ is not affiliated with SSC, RRB, UPSC, DSSSB, NHAI, IBPS or any government department unless expressly stated on a specific listing.",
  "Typing speed, accuracy, certificates or results generated by TAIPOQ are for practice and self-improvement unless an institution explicitly accepts them.",
  "Job update dates, vacancy counts and application windows may change — always verify on official notification PDFs and employer websites.",
  "Official sources prevail over TAIPOQ summaries, translations or display formatting.",
  "Hindi KrutiDev/Remington practice depends on correct font availability and mapping on your device.",
  "TAIPOQ does not guarantee job selection, exam success, or official acceptance of any practice result.",
] as const;

function Disclaimer() {
  return (
    <InfoPage title="Disclaimer">
      <p>
        TAIPOQ helps students and job aspirants practice English and Hindi typing, attempt mock tests,
        and browse verified job updates. It is an independent educational platform.
      </p>
      <InfoList items={POINTS} />
    </InfoPage>
  );
}
