import { createFileRoute } from "@tanstack/react-router";
import { InfoPage, InfoList } from "@/components/InfoPage";

export const Route = createFileRoute("/disclaimer")({
  head: () => ({
    meta: [
      { title: "Disclaimer — TAIPOQ" },
      {
        name: "description",
        content: "Disclaimer for TAIPOQ — important information about practice results and official typing tests.",
      },
    ],
  }),
  component: Disclaimer,
});

const POINTS = [
  "TAIPOQ is not an official government recruitment website.",
  "TAIPOQ is not affiliated with any government department, examination authority, recruitment board, or official typing test authority.",
  "Typing speed, accuracy, certificates, or results generated by TAIPOQ are for practice and self-improvement unless specifically accepted by any institution.",
  "Users should check official exam/job notifications for actual typing test rules, keyboard layout, font requirements, duration, error rules, and qualifying standards.",
  "Hindi KrutiDev/Remington practice depends on correct font availability and mapping. Users should verify requirements for their specific exam or job.",
  "TAIPOQ does not guarantee job selection, exam success, or official acceptance of any result/certificate.",
] as const;

function Disclaimer() {
  return (
    <InfoPage title="Disclaimer">
      <p>
        TAIPOQ is created to help students and job aspirants practice English and Hindi typing. It is an educational/practice platform.
      </p>
      <InfoList items={POINTS} />
    </InfoPage>
  );
}
