/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestRouteImport } from './routes/test'
import { Route as ResultRouteImport } from './routes/result'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HindiRouteImport } from './routes/hindi'
import { Route as EnglishRouteImport } from './routes/english'
import { Route as CertificateRouteImport } from './routes/certificate'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HindiIndexRouteImport } from './routes/hindi.index'
import { Route as EnglishIndexRouteImport } from './routes/english.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as HindiPracticeRouteImport } from './routes/hindi.practice'
import { Route as HindiLessonsRouteImport } from './routes/hindi.lessons'
import { Route as EnglishPracticeRouteImport } from './routes/english.practice'
import { Route as EnglishLessonsRouteImport } from './routes/english.lessons'
import { Route as AdminAddParagraphRouteImport } from './routes/admin.add-paragraph'
import { Route as AdminEditParagraphIdRouteImport } from './routes/admin.edit-paragraph.$id'

const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultRoute = ResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HindiRoute = HindiRouteImport.update({
  id: '/hindi',
  path: '/hindi',
  getParentRoute: () => rootRouteImport,
} as any)
const EnglishRoute = EnglishRouteImport.update({
  id: '/english',
  path: '/english',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificateRoute = CertificateRouteImport.update({
  id: '/certificate',
  path: '/certificate',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HindiIndexRoute = HindiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HindiRoute,
} as any)
const EnglishIndexRoute = EnglishIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EnglishRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const HindiPracticeRoute = HindiPracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => HindiRoute,
} as any)
const HindiLessonsRoute = HindiLessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => HindiRoute,
} as any)
const EnglishPracticeRoute = EnglishPracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => EnglishRoute,
} as any)
const EnglishLessonsRoute = EnglishLessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => EnglishRoute,
} as any)
const AdminAddParagraphRoute = AdminAddParagraphRouteImport.update({
  id: '/add-paragraph',
  path: '/add-paragraph',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEditParagraphIdRoute = AdminEditParagraphIdRouteImport.update({
  id: '/edit-paragraph/$id',
  path: '/edit-paragraph/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/certificate': typeof CertificateRoute
  '/english': typeof EnglishRouteWithChildren
  '/hindi': typeof HindiRouteWithChildren
  '/login': typeof LoginRoute
  '/progress': typeof ProgressRoute
  '/result': typeof ResultRoute
  '/test': typeof TestRoute
  '/admin/add-paragraph': typeof AdminAddParagraphRoute
  '/english/lessons': typeof EnglishLessonsRoute
  '/english/practice': typeof EnglishPracticeRoute
  '/hindi/lessons': typeof HindiLessonsRoute
  '/hindi/practice': typeof HindiPracticeRoute
  '/admin/': typeof AdminIndexRoute
  '/english/': typeof EnglishIndexRoute
  '/hindi/': typeof HindiIndexRoute
  '/admin/edit-paragraph/$id': typeof AdminEditParagraphIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/certificate': typeof CertificateRoute
  '/login': typeof LoginRoute
  '/progress': typeof ProgressRoute
  '/result': typeof ResultRoute
  '/test': typeof TestRoute
  '/admin/add-paragraph': typeof AdminAddParagraphRoute
  '/english/lessons': typeof EnglishLessonsRoute
  '/english/practice': typeof EnglishPracticeRoute
  '/hindi/lessons': typeof HindiLessonsRoute
  '/hindi/practice': typeof HindiPracticeRoute
  '/admin': typeof AdminIndexRoute
  '/english': typeof EnglishIndexRoute
  '/hindi': typeof HindiIndexRoute
  '/admin/edit-paragraph/$id': typeof AdminEditParagraphIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/certificate': typeof CertificateRoute
  '/english': typeof EnglishRouteWithChildren
  '/hindi': typeof HindiRouteWithChildren
  '/login': typeof LoginRoute
  '/progress': typeof ProgressRoute
  '/result': typeof ResultRoute
  '/test': typeof TestRoute
  '/admin/add-paragraph': typeof AdminAddParagraphRoute
  '/english/lessons': typeof EnglishLessonsRoute
  '/english/practice': typeof EnglishPracticeRoute
  '/hindi/lessons': typeof HindiLessonsRoute
  '/hindi/practice': typeof HindiPracticeRoute
  '/admin/': typeof AdminIndexRoute
  '/english/': typeof EnglishIndexRoute
  '/hindi/': typeof HindiIndexRoute
  '/admin/edit-paragraph/$id': typeof AdminEditParagraphIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/certificate'
    | '/english'
    | '/hindi'
    | '/login'
    | '/progress'
    | '/result'
    | '/test'
    | '/admin/add-paragraph'
    | '/english/lessons'
    | '/english/practice'
    | '/hindi/lessons'
    | '/hindi/practice'
    | '/admin/'
    | '/english/'
    | '/hindi/'
    | '/admin/edit-paragraph/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/certificate'
    | '/login'
    | '/progress'
    | '/result'
    | '/test'
    | '/admin/add-paragraph'
    | '/english/lessons'
    | '/english/practice'
    | '/hindi/lessons'
    | '/hindi/practice'
    | '/admin'
    | '/english'
    | '/hindi'
    | '/admin/edit-paragraph/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/certificate'
    | '/english'
    | '/hindi'
    | '/login'
    | '/progress'
    | '/result'
    | '/test'
    | '/admin/add-paragraph'
    | '/english/lessons'
    | '/english/practice'
    | '/hindi/lessons'
    | '/hindi/practice'
    | '/admin/'
    | '/english/'
    | '/hindi/'
    | '/admin/edit-paragraph/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CertificateRoute: typeof CertificateRoute
  EnglishRoute: typeof EnglishRouteWithChildren
  HindiRoute: typeof HindiRouteWithChildren
  LoginRoute: typeof LoginRoute
  ProgressRoute: typeof ProgressRoute
  ResultRoute: typeof ResultRoute
  TestRoute: typeof TestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result': {
      id: '/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hindi': {
      id: '/hindi'
      path: '/hindi'
      fullPath: '/hindi'
      preLoaderRoute: typeof HindiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/english': {
      id: '/english'
      path: '/english'
      fullPath: '/english'
      preLoaderRoute: typeof EnglishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificate': {
      id: '/certificate'
      path: '/certificate'
      fullPath: '/certificate'
      preLoaderRoute: typeof CertificateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hindi/': {
      id: '/hindi/'
      path: '/'
      fullPath: '/hindi/'
      preLoaderRoute: typeof HindiIndexRouteImport
      parentRoute: typeof HindiRoute
    }
    '/english/': {
      id: '/english/'
      path: '/'
      fullPath: '/english/'
      preLoaderRoute: typeof EnglishIndexRouteImport
      parentRoute: typeof EnglishRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/hindi/practice': {
      id: '/hindi/practice'
      path: '/practice'
      fullPath: '/hindi/practice'
      preLoaderRoute: typeof HindiPracticeRouteImport
      parentRoute: typeof HindiRoute
    }
    '/hindi/lessons': {
      id: '/hindi/lessons'
      path: '/lessons'
      fullPath: '/hindi/lessons'
      preLoaderRoute: typeof HindiLessonsRouteImport
      parentRoute: typeof HindiRoute
    }
    '/english/practice': {
      id: '/english/practice'
      path: '/practice'
      fullPath: '/english/practice'
      preLoaderRoute: typeof EnglishPracticeRouteImport
      parentRoute: typeof EnglishRoute
    }
    '/english/lessons': {
      id: '/english/lessons'
      path: '/lessons'
      fullPath: '/english/lessons'
      preLoaderRoute: typeof EnglishLessonsRouteImport
      parentRoute: typeof EnglishRoute
    }
    '/admin/add-paragraph': {
      id: '/admin/add-paragraph'
      path: '/add-paragraph'
      fullPath: '/admin/add-paragraph'
      preLoaderRoute: typeof AdminAddParagraphRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/edit-paragraph/$id': {
      id: '/admin/edit-paragraph/$id'
      path: '/edit-paragraph/$id'
      fullPath: '/admin/edit-paragraph/$id'
      preLoaderRoute: typeof AdminEditParagraphIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAddParagraphRoute: typeof AdminAddParagraphRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminEditParagraphIdRoute: typeof AdminEditParagraphIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAddParagraphRoute: AdminAddParagraphRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminEditParagraphIdRoute: AdminEditParagraphIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface EnglishRouteChildren {
  EnglishLessonsRoute: typeof EnglishLessonsRoute
  EnglishPracticeRoute: typeof EnglishPracticeRoute
  EnglishIndexRoute: typeof EnglishIndexRoute
}

const EnglishRouteChildren: EnglishRouteChildren = {
  EnglishLessonsRoute: EnglishLessonsRoute,
  EnglishPracticeRoute: EnglishPracticeRoute,
  EnglishIndexRoute: EnglishIndexRoute,
}

const EnglishRouteWithChildren =
  EnglishRoute._addFileChildren(EnglishRouteChildren)

interface HindiRouteChildren {
  HindiLessonsRoute: typeof HindiLessonsRoute
  HindiPracticeRoute: typeof HindiPracticeRoute
  HindiIndexRoute: typeof HindiIndexRoute
}

const HindiRouteChildren: HindiRouteChildren = {
  HindiLessonsRoute: HindiLessonsRoute,
  HindiPracticeRoute: HindiPracticeRoute,
  HindiIndexRoute: HindiIndexRoute,
}

const HindiRouteWithChildren = HindiRoute._addFileChildren(HindiRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CertificateRoute: CertificateRoute,
  EnglishRoute: EnglishRouteWithChildren,
  HindiRoute: HindiRouteWithChildren,
  LoginRoute: LoginRoute,
  ProgressRoute: ProgressRoute,
  ResultRoute: ResultRoute,
  TestRoute: TestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
