/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WordLearningRouteImport } from './routes/word-learning'
import { Route as UpcomingExamsRouteImport } from './routes/upcoming-exams'
import { Route as TypingTipsRouteImport } from './routes/typing-tips'
import { Route as TypingStartGuideRouteImport } from './routes/typing-start-guide'
import { Route as TestRouteImport } from './routes/test'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StudyCornerRouteImport } from './routes/study-corner'
import { Route as ResultRouteImport } from './routes/result'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HindiRouteImport } from './routes/hindi'
import { Route as EnglishRouteImport } from './routes/english'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CertificateRouteImport } from './routes/certificate'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudyCornerIndexRouteImport } from './routes/study-corner.index'
import { Route as HindiIndexRouteImport } from './routes/hindi.index'
import { Route as EnglishIndexRouteImport } from './routes/english.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as StudyCornerQuizResultRouteImport } from './routes/study-corner.quiz-result'
import { Route as StudyCornerGeneralAwarenessRouteImport } from './routes/study-corner.general-awareness'
import { Route as StudyCornerComputerBasicsRouteImport } from './routes/study-corner.computer-basics'
import { Route as HindiPracticeRouteImport } from './routes/hindi.practice'
import { Route as HindiLessonsRouteImport } from './routes/hindi.lessons'
import { Route as EnglishPracticeRouteImport } from './routes/english.practice'
import { Route as EnglishLessonsRouteImport } from './routes/english.lessons'
import { Route as AdminAddParagraphRouteImport } from './routes/admin.add-paragraph'
import { Route as StudyCornerGeneralAwarenessIndexRouteImport } from './routes/study-corner.general-awareness.index'
import { Route as StudyCornerComputerBasicsIndexRouteImport } from './routes/study-corner.computer-basics.index'
import { Route as StudyCornerGeneralAwarenessChapter6RouteImport } from './routes/study-corner.general-awareness.chapter-6'
import { Route as StudyCornerGeneralAwarenessChapter5RouteImport } from './routes/study-corner.general-awareness.chapter-5'
import { Route as StudyCornerGeneralAwarenessChapter4RouteImport } from './routes/study-corner.general-awareness.chapter-4'
import { Route as StudyCornerGeneralAwarenessChapter3RouteImport } from './routes/study-corner.general-awareness.chapter-3'
import { Route as StudyCornerGeneralAwarenessChapter2RouteImport } from './routes/study-corner.general-awareness.chapter-2'
import { Route as StudyCornerGeneralAwarenessChapter1RouteImport } from './routes/study-corner.general-awareness.chapter-1'
import { Route as StudyCornerComputerBasicsWordBasicKnowledgeRouteImport } from './routes/study-corner.computer-basics.word-basic-knowledge'
import { Route as StudyCornerComputerBasicsExcelBasicKnowledgeRouteImport } from './routes/study-corner.computer-basics.excel-basic-knowledge'
import { Route as StudyCornerComputerBasicsChapter5RouteImport } from './routes/study-corner.computer-basics.chapter-5'
import { Route as StudyCornerComputerBasicsChapter4RouteImport } from './routes/study-corner.computer-basics.chapter-4'
import { Route as StudyCornerComputerBasicsChapter3RouteImport } from './routes/study-corner.computer-basics.chapter-3'
import { Route as StudyCornerComputerBasicsChapter2RouteImport } from './routes/study-corner.computer-basics.chapter-2'
import { Route as StudyCornerComputerBasicsChapter1RouteImport } from './routes/study-corner.computer-basics.chapter-1'
import { Route as AdminEditParagraphIdRouteImport } from './routes/admin.edit-paragraph.$id'

const WordLearningRoute = WordLearningRouteImport.update({
  id: '/word-learning',
  path: '/word-learning',
  getParentRoute: () => rootRouteImport,
} as any)
const UpcomingExamsRoute = UpcomingExamsRouteImport.update({
  id: '/upcoming-exams',
  path: '/upcoming-exams',
  getParentRoute: () => rootRouteImport,
} as any)
const TypingTipsRoute = TypingTipsRouteImport.update({
  id: '/typing-tips',
  path: '/typing-tips',
  getParentRoute: () => rootRouteImport,
} as any)
const TypingStartGuideRoute = TypingStartGuideRouteImport.update({
  id: '/typing-start-guide',
  path: '/typing-start-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyCornerRoute = StudyCornerRouteImport.update({
  id: '/study-corner',
  path: '/study-corner',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultRoute = ResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HindiRoute = HindiRouteImport.update({
  id: '/hindi',
  path: '/hindi',
  getParentRoute: () => rootRouteImport,
} as any)
const EnglishRoute = EnglishRouteImport.update({
  id: '/english',
  path: '/english',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificateRoute = CertificateRouteImport.update({
  id: '/certificate',
  path: '/certificate',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyCornerIndexRoute = StudyCornerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudyCornerRoute,
} as any)
const HindiIndexRoute = HindiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HindiRoute,
} as any)
const EnglishIndexRoute = EnglishIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EnglishRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const StudyCornerQuizResultRoute = StudyCornerQuizResultRouteImport.update({
  id: '/quiz-result',
  path: '/quiz-result',
  getParentRoute: () => StudyCornerRoute,
} as any)
const StudyCornerGeneralAwarenessRoute =
  StudyCornerGeneralAwarenessRouteImport.update({
    id: '/general-awareness',
    path: '/general-awareness',
    getParentRoute: () => StudyCornerRoute,
  } as any)
const StudyCornerComputerBasicsRoute =
  StudyCornerComputerBasicsRouteImport.update({
    id: '/computer-basics',
    path: '/computer-basics',
    getParentRoute: () => StudyCornerRoute,
  } as any)
const HindiPracticeRoute = HindiPracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => HindiRoute,
} as any)
const HindiLessonsRoute = HindiLessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => HindiRoute,
} as any)
const EnglishPracticeRoute = EnglishPracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => EnglishRoute,
} as any)
const EnglishLessonsRoute = EnglishLessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => EnglishRoute,
} as any)
const AdminAddParagraphRoute = AdminAddParagraphRouteImport.update({
  id: '/add-paragraph',
  path: '/add-paragraph',
  getParentRoute: () => AdminRoute,
} as any)
const StudyCornerGeneralAwarenessIndexRoute =
  StudyCornerGeneralAwarenessIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => StudyCornerGeneralAwarenessRoute,
  } as any)
const StudyCornerComputerBasicsIndexRoute =
  StudyCornerComputerBasicsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => StudyCornerComputerBasicsRoute,
  } as any)
const StudyCornerGeneralAwarenessChapter6Route =
  StudyCornerGeneralAwarenessChapter6RouteImport.update({
    id: '/chapter-6',
    path: '/chapter-6',
    getParentRoute: () => StudyCornerGeneralAwarenessRoute,
  } as any)
const StudyCornerGeneralAwarenessChapter5Route =
  StudyCornerGeneralAwarenessChapter5RouteImport.update({
    id: '/chapter-5',
    path: '/chapter-5',
    getParentRoute: () => StudyCornerGeneralAwarenessRoute,
  } as any)
const StudyCornerGeneralAwarenessChapter4Route =
  StudyCornerGeneralAwarenessChapter4RouteImport.update({
    id: '/chapter-4',
    path: '/chapter-4',
    getParentRoute: () => StudyCornerGeneralAwarenessRoute,
  } as any)
const StudyCornerGeneralAwarenessChapter3Route =
  StudyCornerGeneralAwarenessChapter3RouteImport.update({
    id: '/chapter-3',
    path: '/chapter-3',
    getParentRoute: () => StudyCornerGeneralAwarenessRoute,
  } as any)
const StudyCornerGeneralAwarenessChapter2Route =
  StudyCornerGeneralAwarenessChapter2RouteImport.update({
    id: '/chapter-2',
    path: '/chapter-2',
    getParentRoute: () => StudyCornerGeneralAwarenessRoute,
  } as any)
const StudyCornerGeneralAwarenessChapter1Route =
  StudyCornerGeneralAwarenessChapter1RouteImport.update({
    id: '/chapter-1',
    path: '/chapter-1',
    getParentRoute: () => StudyCornerGeneralAwarenessRoute,
  } as any)
const StudyCornerComputerBasicsWordBasicKnowledgeRoute =
  StudyCornerComputerBasicsWordBasicKnowledgeRouteImport.update({
    id: '/word-basic-knowledge',
    path: '/word-basic-knowledge',
    getParentRoute: () => StudyCornerComputerBasicsRoute,
  } as any)
const StudyCornerComputerBasicsExcelBasicKnowledgeRoute =
  StudyCornerComputerBasicsExcelBasicKnowledgeRouteImport.update({
    id: '/excel-basic-knowledge',
    path: '/excel-basic-knowledge',
    getParentRoute: () => StudyCornerComputerBasicsRoute,
  } as any)
const StudyCornerComputerBasicsChapter5Route =
  StudyCornerComputerBasicsChapter5RouteImport.update({
    id: '/chapter-5',
    path: '/chapter-5',
    getParentRoute: () => StudyCornerComputerBasicsRoute,
  } as any)
const StudyCornerComputerBasicsChapter4Route =
  StudyCornerComputerBasicsChapter4RouteImport.update({
    id: '/chapter-4',
    path: '/chapter-4',
    getParentRoute: () => StudyCornerComputerBasicsRoute,
  } as any)
const StudyCornerComputerBasicsChapter3Route =
  StudyCornerComputerBasicsChapter3RouteImport.update({
    id: '/chapter-3',
    path: '/chapter-3',
    getParentRoute: () => StudyCornerComputerBasicsRoute,
  } as any)
const StudyCornerComputerBasicsChapter2Route =
  StudyCornerComputerBasicsChapter2RouteImport.update({
    id: '/chapter-2',
    path: '/chapter-2',
    getParentRoute: () => StudyCornerComputerBasicsRoute,
  } as any)
const StudyCornerComputerBasicsChapter1Route =
  StudyCornerComputerBasicsChapter1RouteImport.update({
    id: '/chapter-1',
    path: '/chapter-1',
    getParentRoute: () => StudyCornerComputerBasicsRoute,
  } as any)
const AdminEditParagraphIdRoute = AdminEditParagraphIdRouteImport.update({
  id: '/edit-paragraph/$id',
  path: '/edit-paragraph/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/certificate': typeof CertificateRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/english': typeof EnglishRouteWithChildren
  '/hindi': typeof HindiRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/progress': typeof ProgressRoute
  '/result': typeof ResultRoute
  '/study-corner': typeof StudyCornerRouteWithChildren
  '/terms': typeof TermsRoute
  '/test': typeof TestRoute
  '/typing-start-guide': typeof TypingStartGuideRoute
  '/typing-tips': typeof TypingTipsRoute
  '/upcoming-exams': typeof UpcomingExamsRoute
  '/word-learning': typeof WordLearningRoute
  '/admin/add-paragraph': typeof AdminAddParagraphRoute
  '/english/lessons': typeof EnglishLessonsRoute
  '/english/practice': typeof EnglishPracticeRoute
  '/hindi/lessons': typeof HindiLessonsRoute
  '/hindi/practice': typeof HindiPracticeRoute
  '/study-corner/computer-basics': typeof StudyCornerComputerBasicsRouteWithChildren
  '/study-corner/general-awareness': typeof StudyCornerGeneralAwarenessRouteWithChildren
  '/study-corner/quiz-result': typeof StudyCornerQuizResultRoute
  '/admin/': typeof AdminIndexRoute
  '/english/': typeof EnglishIndexRoute
  '/hindi/': typeof HindiIndexRoute
  '/study-corner/': typeof StudyCornerIndexRoute
  '/admin/edit-paragraph/$id': typeof AdminEditParagraphIdRoute
  '/study-corner/computer-basics/chapter-1': typeof StudyCornerComputerBasicsChapter1Route
  '/study-corner/computer-basics/chapter-2': typeof StudyCornerComputerBasicsChapter2Route
  '/study-corner/computer-basics/chapter-3': typeof StudyCornerComputerBasicsChapter3Route
  '/study-corner/computer-basics/chapter-4': typeof StudyCornerComputerBasicsChapter4Route
  '/study-corner/computer-basics/chapter-5': typeof StudyCornerComputerBasicsChapter5Route
  '/study-corner/computer-basics/excel-basic-knowledge': typeof StudyCornerComputerBasicsExcelBasicKnowledgeRoute
  '/study-corner/computer-basics/word-basic-knowledge': typeof StudyCornerComputerBasicsWordBasicKnowledgeRoute
  '/study-corner/general-awareness/chapter-1': typeof StudyCornerGeneralAwarenessChapter1Route
  '/study-corner/general-awareness/chapter-2': typeof StudyCornerGeneralAwarenessChapter2Route
  '/study-corner/general-awareness/chapter-3': typeof StudyCornerGeneralAwarenessChapter3Route
  '/study-corner/general-awareness/chapter-4': typeof StudyCornerGeneralAwarenessChapter4Route
  '/study-corner/general-awareness/chapter-5': typeof StudyCornerGeneralAwarenessChapter5Route
  '/study-corner/general-awareness/chapter-6': typeof StudyCornerGeneralAwarenessChapter6Route
  '/study-corner/computer-basics/': typeof StudyCornerComputerBasicsIndexRoute
  '/study-corner/general-awareness/': typeof StudyCornerGeneralAwarenessIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/certificate': typeof CertificateRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/progress': typeof ProgressRoute
  '/result': typeof ResultRoute
  '/terms': typeof TermsRoute
  '/test': typeof TestRoute
  '/typing-start-guide': typeof TypingStartGuideRoute
  '/typing-tips': typeof TypingTipsRoute
  '/upcoming-exams': typeof UpcomingExamsRoute
  '/word-learning': typeof WordLearningRoute
  '/admin/add-paragraph': typeof AdminAddParagraphRoute
  '/english/lessons': typeof EnglishLessonsRoute
  '/english/practice': typeof EnglishPracticeRoute
  '/hindi/lessons': typeof HindiLessonsRoute
  '/hindi/practice': typeof HindiPracticeRoute
  '/study-corner/quiz-result': typeof StudyCornerQuizResultRoute
  '/admin': typeof AdminIndexRoute
  '/english': typeof EnglishIndexRoute
  '/hindi': typeof HindiIndexRoute
  '/study-corner': typeof StudyCornerIndexRoute
  '/admin/edit-paragraph/$id': typeof AdminEditParagraphIdRoute
  '/study-corner/computer-basics/chapter-1': typeof StudyCornerComputerBasicsChapter1Route
  '/study-corner/computer-basics/chapter-2': typeof StudyCornerComputerBasicsChapter2Route
  '/study-corner/computer-basics/chapter-3': typeof StudyCornerComputerBasicsChapter3Route
  '/study-corner/computer-basics/chapter-4': typeof StudyCornerComputerBasicsChapter4Route
  '/study-corner/computer-basics/chapter-5': typeof StudyCornerComputerBasicsChapter5Route
  '/study-corner/computer-basics/excel-basic-knowledge': typeof StudyCornerComputerBasicsExcelBasicKnowledgeRoute
  '/study-corner/computer-basics/word-basic-knowledge': typeof StudyCornerComputerBasicsWordBasicKnowledgeRoute
  '/study-corner/general-awareness/chapter-1': typeof StudyCornerGeneralAwarenessChapter1Route
  '/study-corner/general-awareness/chapter-2': typeof StudyCornerGeneralAwarenessChapter2Route
  '/study-corner/general-awareness/chapter-3': typeof StudyCornerGeneralAwarenessChapter3Route
  '/study-corner/general-awareness/chapter-4': typeof StudyCornerGeneralAwarenessChapter4Route
  '/study-corner/general-awareness/chapter-5': typeof StudyCornerGeneralAwarenessChapter5Route
  '/study-corner/general-awareness/chapter-6': typeof StudyCornerGeneralAwarenessChapter6Route
  '/study-corner/computer-basics': typeof StudyCornerComputerBasicsIndexRoute
  '/study-corner/general-awareness': typeof StudyCornerGeneralAwarenessIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/certificate': typeof CertificateRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/english': typeof EnglishRouteWithChildren
  '/hindi': typeof HindiRouteWithChildren
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/progress': typeof ProgressRoute
  '/result': typeof ResultRoute
  '/study-corner': typeof StudyCornerRouteWithChildren
  '/terms': typeof TermsRoute
  '/test': typeof TestRoute
  '/typing-start-guide': typeof TypingStartGuideRoute
  '/typing-tips': typeof TypingTipsRoute
  '/upcoming-exams': typeof UpcomingExamsRoute
  '/word-learning': typeof WordLearningRoute
  '/admin/add-paragraph': typeof AdminAddParagraphRoute
  '/english/lessons': typeof EnglishLessonsRoute
  '/english/practice': typeof EnglishPracticeRoute
  '/hindi/lessons': typeof HindiLessonsRoute
  '/hindi/practice': typeof HindiPracticeRoute
  '/study-corner/computer-basics': typeof StudyCornerComputerBasicsRouteWithChildren
  '/study-corner/general-awareness': typeof StudyCornerGeneralAwarenessRouteWithChildren
  '/study-corner/quiz-result': typeof StudyCornerQuizResultRoute
  '/admin/': typeof AdminIndexRoute
  '/english/': typeof EnglishIndexRoute
  '/hindi/': typeof HindiIndexRoute
  '/study-corner/': typeof StudyCornerIndexRoute
  '/admin/edit-paragraph/$id': typeof AdminEditParagraphIdRoute
  '/study-corner/computer-basics/chapter-1': typeof StudyCornerComputerBasicsChapter1Route
  '/study-corner/computer-basics/chapter-2': typeof StudyCornerComputerBasicsChapter2Route
  '/study-corner/computer-basics/chapter-3': typeof StudyCornerComputerBasicsChapter3Route
  '/study-corner/computer-basics/chapter-4': typeof StudyCornerComputerBasicsChapter4Route
  '/study-corner/computer-basics/chapter-5': typeof StudyCornerComputerBasicsChapter5Route
  '/study-corner/computer-basics/excel-basic-knowledge': typeof StudyCornerComputerBasicsExcelBasicKnowledgeRoute
  '/study-corner/computer-basics/word-basic-knowledge': typeof StudyCornerComputerBasicsWordBasicKnowledgeRoute
  '/study-corner/general-awareness/chapter-1': typeof StudyCornerGeneralAwarenessChapter1Route
  '/study-corner/general-awareness/chapter-2': typeof StudyCornerGeneralAwarenessChapter2Route
  '/study-corner/general-awareness/chapter-3': typeof StudyCornerGeneralAwarenessChapter3Route
  '/study-corner/general-awareness/chapter-4': typeof StudyCornerGeneralAwarenessChapter4Route
  '/study-corner/general-awareness/chapter-5': typeof StudyCornerGeneralAwarenessChapter5Route
  '/study-corner/general-awareness/chapter-6': typeof StudyCornerGeneralAwarenessChapter6Route
  '/study-corner/computer-basics/': typeof StudyCornerComputerBasicsIndexRoute
  '/study-corner/general-awareness/': typeof StudyCornerGeneralAwarenessIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/certificate'
    | '/contact'
    | '/disclaimer'
    | '/english'
    | '/hindi'
    | '/login'
    | '/privacy-policy'
    | '/progress'
    | '/result'
    | '/study-corner'
    | '/terms'
    | '/test'
    | '/typing-start-guide'
    | '/typing-tips'
    | '/upcoming-exams'
    | '/word-learning'
    | '/admin/add-paragraph'
    | '/english/lessons'
    | '/english/practice'
    | '/hindi/lessons'
    | '/hindi/practice'
    | '/study-corner/computer-basics'
    | '/study-corner/general-awareness'
    | '/study-corner/quiz-result'
    | '/admin/'
    | '/english/'
    | '/hindi/'
    | '/study-corner/'
    | '/admin/edit-paragraph/$id'
    | '/study-corner/computer-basics/chapter-1'
    | '/study-corner/computer-basics/chapter-2'
    | '/study-corner/computer-basics/chapter-3'
    | '/study-corner/computer-basics/chapter-4'
    | '/study-corner/computer-basics/chapter-5'
    | '/study-corner/computer-basics/excel-basic-knowledge'
    | '/study-corner/computer-basics/word-basic-knowledge'
    | '/study-corner/general-awareness/chapter-1'
    | '/study-corner/general-awareness/chapter-2'
    | '/study-corner/general-awareness/chapter-3'
    | '/study-corner/general-awareness/chapter-4'
    | '/study-corner/general-awareness/chapter-5'
    | '/study-corner/general-awareness/chapter-6'
    | '/study-corner/computer-basics/'
    | '/study-corner/general-awareness/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/certificate'
    | '/contact'
    | '/disclaimer'
    | '/login'
    | '/privacy-policy'
    | '/progress'
    | '/result'
    | '/terms'
    | '/test'
    | '/typing-start-guide'
    | '/typing-tips'
    | '/upcoming-exams'
    | '/word-learning'
    | '/admin/add-paragraph'
    | '/english/lessons'
    | '/english/practice'
    | '/hindi/lessons'
    | '/hindi/practice'
    | '/study-corner/quiz-result'
    | '/admin'
    | '/english'
    | '/hindi'
    | '/study-corner'
    | '/admin/edit-paragraph/$id'
    | '/study-corner/computer-basics/chapter-1'
    | '/study-corner/computer-basics/chapter-2'
    | '/study-corner/computer-basics/chapter-3'
    | '/study-corner/computer-basics/chapter-4'
    | '/study-corner/computer-basics/chapter-5'
    | '/study-corner/computer-basics/excel-basic-knowledge'
    | '/study-corner/computer-basics/word-basic-knowledge'
    | '/study-corner/general-awareness/chapter-1'
    | '/study-corner/general-awareness/chapter-2'
    | '/study-corner/general-awareness/chapter-3'
    | '/study-corner/general-awareness/chapter-4'
    | '/study-corner/general-awareness/chapter-5'
    | '/study-corner/general-awareness/chapter-6'
    | '/study-corner/computer-basics'
    | '/study-corner/general-awareness'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/certificate'
    | '/contact'
    | '/disclaimer'
    | '/english'
    | '/hindi'
    | '/login'
    | '/privacy-policy'
    | '/progress'
    | '/result'
    | '/study-corner'
    | '/terms'
    | '/test'
    | '/typing-start-guide'
    | '/typing-tips'
    | '/upcoming-exams'
    | '/word-learning'
    | '/admin/add-paragraph'
    | '/english/lessons'
    | '/english/practice'
    | '/hindi/lessons'
    | '/hindi/practice'
    | '/study-corner/computer-basics'
    | '/study-corner/general-awareness'
    | '/study-corner/quiz-result'
    | '/admin/'
    | '/english/'
    | '/hindi/'
    | '/study-corner/'
    | '/admin/edit-paragraph/$id'
    | '/study-corner/computer-basics/chapter-1'
    | '/study-corner/computer-basics/chapter-2'
    | '/study-corner/computer-basics/chapter-3'
    | '/study-corner/computer-basics/chapter-4'
    | '/study-corner/computer-basics/chapter-5'
    | '/study-corner/computer-basics/excel-basic-knowledge'
    | '/study-corner/computer-basics/word-basic-knowledge'
    | '/study-corner/general-awareness/chapter-1'
    | '/study-corner/general-awareness/chapter-2'
    | '/study-corner/general-awareness/chapter-3'
    | '/study-corner/general-awareness/chapter-4'
    | '/study-corner/general-awareness/chapter-5'
    | '/study-corner/general-awareness/chapter-6'
    | '/study-corner/computer-basics/'
    | '/study-corner/general-awareness/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  CertificateRoute: typeof CertificateRoute
  ContactRoute: typeof ContactRoute
  DisclaimerRoute: typeof DisclaimerRoute
  EnglishRoute: typeof EnglishRouteWithChildren
  HindiRoute: typeof HindiRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ProgressRoute: typeof ProgressRoute
  ResultRoute: typeof ResultRoute
  StudyCornerRoute: typeof StudyCornerRouteWithChildren
  TermsRoute: typeof TermsRoute
  TestRoute: typeof TestRoute
  TypingStartGuideRoute: typeof TypingStartGuideRoute
  TypingTipsRoute: typeof TypingTipsRoute
  UpcomingExamsRoute: typeof UpcomingExamsRoute
  WordLearningRoute: typeof WordLearningRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/word-learning': {
      id: '/word-learning'
      path: '/word-learning'
      fullPath: '/word-learning'
      preLoaderRoute: typeof WordLearningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upcoming-exams': {
      id: '/upcoming-exams'
      path: '/upcoming-exams'
      fullPath: '/upcoming-exams'
      preLoaderRoute: typeof UpcomingExamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/typing-tips': {
      id: '/typing-tips'
      path: '/typing-tips'
      fullPath: '/typing-tips'
      preLoaderRoute: typeof TypingTipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/typing-start-guide': {
      id: '/typing-start-guide'
      path: '/typing-start-guide'
      fullPath: '/typing-start-guide'
      preLoaderRoute: typeof TypingStartGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study-corner': {
      id: '/study-corner'
      path: '/study-corner'
      fullPath: '/study-corner'
      preLoaderRoute: typeof StudyCornerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result': {
      id: '/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hindi': {
      id: '/hindi'
      path: '/hindi'
      fullPath: '/hindi'
      preLoaderRoute: typeof HindiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/english': {
      id: '/english'
      path: '/english'
      fullPath: '/english'
      preLoaderRoute: typeof EnglishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificate': {
      id: '/certificate'
      path: '/certificate'
      fullPath: '/certificate'
      preLoaderRoute: typeof CertificateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study-corner/': {
      id: '/study-corner/'
      path: '/'
      fullPath: '/study-corner/'
      preLoaderRoute: typeof StudyCornerIndexRouteImport
      parentRoute: typeof StudyCornerRoute
    }
    '/hindi/': {
      id: '/hindi/'
      path: '/'
      fullPath: '/hindi/'
      preLoaderRoute: typeof HindiIndexRouteImport
      parentRoute: typeof HindiRoute
    }
    '/english/': {
      id: '/english/'
      path: '/'
      fullPath: '/english/'
      preLoaderRoute: typeof EnglishIndexRouteImport
      parentRoute: typeof EnglishRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/study-corner/quiz-result': {
      id: '/study-corner/quiz-result'
      path: '/quiz-result'
      fullPath: '/study-corner/quiz-result'
      preLoaderRoute: typeof StudyCornerQuizResultRouteImport
      parentRoute: typeof StudyCornerRoute
    }
    '/study-corner/general-awareness': {
      id: '/study-corner/general-awareness'
      path: '/general-awareness'
      fullPath: '/study-corner/general-awareness'
      preLoaderRoute: typeof StudyCornerGeneralAwarenessRouteImport
      parentRoute: typeof StudyCornerRoute
    }
    '/study-corner/computer-basics': {
      id: '/study-corner/computer-basics'
      path: '/computer-basics'
      fullPath: '/study-corner/computer-basics'
      preLoaderRoute: typeof StudyCornerComputerBasicsRouteImport
      parentRoute: typeof StudyCornerRoute
    }
    '/hindi/practice': {
      id: '/hindi/practice'
      path: '/practice'
      fullPath: '/hindi/practice'
      preLoaderRoute: typeof HindiPracticeRouteImport
      parentRoute: typeof HindiRoute
    }
    '/hindi/lessons': {
      id: '/hindi/lessons'
      path: '/lessons'
      fullPath: '/hindi/lessons'
      preLoaderRoute: typeof HindiLessonsRouteImport
      parentRoute: typeof HindiRoute
    }
    '/english/practice': {
      id: '/english/practice'
      path: '/practice'
      fullPath: '/english/practice'
      preLoaderRoute: typeof EnglishPracticeRouteImport
      parentRoute: typeof EnglishRoute
    }
    '/english/lessons': {
      id: '/english/lessons'
      path: '/lessons'
      fullPath: '/english/lessons'
      preLoaderRoute: typeof EnglishLessonsRouteImport
      parentRoute: typeof EnglishRoute
    }
    '/admin/add-paragraph': {
      id: '/admin/add-paragraph'
      path: '/add-paragraph'
      fullPath: '/admin/add-paragraph'
      preLoaderRoute: typeof AdminAddParagraphRouteImport
      parentRoute: typeof AdminRoute
    }
    '/study-corner/general-awareness/': {
      id: '/study-corner/general-awareness/'
      path: '/'
      fullPath: '/study-corner/general-awareness/'
      preLoaderRoute: typeof StudyCornerGeneralAwarenessIndexRouteImport
      parentRoute: typeof StudyCornerGeneralAwarenessRoute
    }
    '/study-corner/computer-basics/': {
      id: '/study-corner/computer-basics/'
      path: '/'
      fullPath: '/study-corner/computer-basics/'
      preLoaderRoute: typeof StudyCornerComputerBasicsIndexRouteImport
      parentRoute: typeof StudyCornerComputerBasicsRoute
    }
    '/study-corner/general-awareness/chapter-6': {
      id: '/study-corner/general-awareness/chapter-6'
      path: '/chapter-6'
      fullPath: '/study-corner/general-awareness/chapter-6'
      preLoaderRoute: typeof StudyCornerGeneralAwarenessChapter6RouteImport
      parentRoute: typeof StudyCornerGeneralAwarenessRoute
    }
    '/study-corner/general-awareness/chapter-5': {
      id: '/study-corner/general-awareness/chapter-5'
      path: '/chapter-5'
      fullPath: '/study-corner/general-awareness/chapter-5'
      preLoaderRoute: typeof StudyCornerGeneralAwarenessChapter5RouteImport
      parentRoute: typeof StudyCornerGeneralAwarenessRoute
    }
    '/study-corner/general-awareness/chapter-4': {
      id: '/study-corner/general-awareness/chapter-4'
      path: '/chapter-4'
      fullPath: '/study-corner/general-awareness/chapter-4'
      preLoaderRoute: typeof StudyCornerGeneralAwarenessChapter4RouteImport
      parentRoute: typeof StudyCornerGeneralAwarenessRoute
    }
    '/study-corner/general-awareness/chapter-3': {
      id: '/study-corner/general-awareness/chapter-3'
      path: '/chapter-3'
      fullPath: '/study-corner/general-awareness/chapter-3'
      preLoaderRoute: typeof StudyCornerGeneralAwarenessChapter3RouteImport
      parentRoute: typeof StudyCornerGeneralAwarenessRoute
    }
    '/study-corner/general-awareness/chapter-2': {
      id: '/study-corner/general-awareness/chapter-2'
      path: '/chapter-2'
      fullPath: '/study-corner/general-awareness/chapter-2'
      preLoaderRoute: typeof StudyCornerGeneralAwarenessChapter2RouteImport
      parentRoute: typeof StudyCornerGeneralAwarenessRoute
    }
    '/study-corner/general-awareness/chapter-1': {
      id: '/study-corner/general-awareness/chapter-1'
      path: '/chapter-1'
      fullPath: '/study-corner/general-awareness/chapter-1'
      preLoaderRoute: typeof StudyCornerGeneralAwarenessChapter1RouteImport
      parentRoute: typeof StudyCornerGeneralAwarenessRoute
    }
    '/study-corner/computer-basics/word-basic-knowledge': {
      id: '/study-corner/computer-basics/word-basic-knowledge'
      path: '/word-basic-knowledge'
      fullPath: '/study-corner/computer-basics/word-basic-knowledge'
      preLoaderRoute: typeof StudyCornerComputerBasicsWordBasicKnowledgeRouteImport
      parentRoute: typeof StudyCornerComputerBasicsRoute
    }
    '/study-corner/computer-basics/excel-basic-knowledge': {
      id: '/study-corner/computer-basics/excel-basic-knowledge'
      path: '/excel-basic-knowledge'
      fullPath: '/study-corner/computer-basics/excel-basic-knowledge'
      preLoaderRoute: typeof StudyCornerComputerBasicsExcelBasicKnowledgeRouteImport
      parentRoute: typeof StudyCornerComputerBasicsRoute
    }
    '/study-corner/computer-basics/chapter-5': {
      id: '/study-corner/computer-basics/chapter-5'
      path: '/chapter-5'
      fullPath: '/study-corner/computer-basics/chapter-5'
      preLoaderRoute: typeof StudyCornerComputerBasicsChapter5RouteImport
      parentRoute: typeof StudyCornerComputerBasicsRoute
    }
    '/study-corner/computer-basics/chapter-4': {
      id: '/study-corner/computer-basics/chapter-4'
      path: '/chapter-4'
      fullPath: '/study-corner/computer-basics/chapter-4'
      preLoaderRoute: typeof StudyCornerComputerBasicsChapter4RouteImport
      parentRoute: typeof StudyCornerComputerBasicsRoute
    }
    '/study-corner/computer-basics/chapter-3': {
      id: '/study-corner/computer-basics/chapter-3'
      path: '/chapter-3'
      fullPath: '/study-corner/computer-basics/chapter-3'
      preLoaderRoute: typeof StudyCornerComputerBasicsChapter3RouteImport
      parentRoute: typeof StudyCornerComputerBasicsRoute
    }
    '/study-corner/computer-basics/chapter-2': {
      id: '/study-corner/computer-basics/chapter-2'
      path: '/chapter-2'
      fullPath: '/study-corner/computer-basics/chapter-2'
      preLoaderRoute: typeof StudyCornerComputerBasicsChapter2RouteImport
      parentRoute: typeof StudyCornerComputerBasicsRoute
    }
    '/study-corner/computer-basics/chapter-1': {
      id: '/study-corner/computer-basics/chapter-1'
      path: '/chapter-1'
      fullPath: '/study-corner/computer-basics/chapter-1'
      preLoaderRoute: typeof StudyCornerComputerBasicsChapter1RouteImport
      parentRoute: typeof StudyCornerComputerBasicsRoute
    }
    '/admin/edit-paragraph/$id': {
      id: '/admin/edit-paragraph/$id'
      path: '/edit-paragraph/$id'
      fullPath: '/admin/edit-paragraph/$id'
      preLoaderRoute: typeof AdminEditParagraphIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAddParagraphRoute: typeof AdminAddParagraphRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminEditParagraphIdRoute: typeof AdminEditParagraphIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAddParagraphRoute: AdminAddParagraphRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminEditParagraphIdRoute: AdminEditParagraphIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface EnglishRouteChildren {
  EnglishLessonsRoute: typeof EnglishLessonsRoute
  EnglishPracticeRoute: typeof EnglishPracticeRoute
  EnglishIndexRoute: typeof EnglishIndexRoute
}

const EnglishRouteChildren: EnglishRouteChildren = {
  EnglishLessonsRoute: EnglishLessonsRoute,
  EnglishPracticeRoute: EnglishPracticeRoute,
  EnglishIndexRoute: EnglishIndexRoute,
}

const EnglishRouteWithChildren =
  EnglishRoute._addFileChildren(EnglishRouteChildren)

interface HindiRouteChildren {
  HindiLessonsRoute: typeof HindiLessonsRoute
  HindiPracticeRoute: typeof HindiPracticeRoute
  HindiIndexRoute: typeof HindiIndexRoute
}

const HindiRouteChildren: HindiRouteChildren = {
  HindiLessonsRoute: HindiLessonsRoute,
  HindiPracticeRoute: HindiPracticeRoute,
  HindiIndexRoute: HindiIndexRoute,
}

const HindiRouteWithChildren = HindiRoute._addFileChildren(HindiRouteChildren)

interface StudyCornerComputerBasicsRouteChildren {
  StudyCornerComputerBasicsChapter1Route: typeof StudyCornerComputerBasicsChapter1Route
  StudyCornerComputerBasicsChapter2Route: typeof StudyCornerComputerBasicsChapter2Route
  StudyCornerComputerBasicsChapter3Route: typeof StudyCornerComputerBasicsChapter3Route
  StudyCornerComputerBasicsChapter4Route: typeof StudyCornerComputerBasicsChapter4Route
  StudyCornerComputerBasicsChapter5Route: typeof StudyCornerComputerBasicsChapter5Route
  StudyCornerComputerBasicsExcelBasicKnowledgeRoute: typeof StudyCornerComputerBasicsExcelBasicKnowledgeRoute
  StudyCornerComputerBasicsWordBasicKnowledgeRoute: typeof StudyCornerComputerBasicsWordBasicKnowledgeRoute
  StudyCornerComputerBasicsIndexRoute: typeof StudyCornerComputerBasicsIndexRoute
}

const StudyCornerComputerBasicsRouteChildren: StudyCornerComputerBasicsRouteChildren =
  {
    StudyCornerComputerBasicsChapter1Route:
      StudyCornerComputerBasicsChapter1Route,
    StudyCornerComputerBasicsChapter2Route:
      StudyCornerComputerBasicsChapter2Route,
    StudyCornerComputerBasicsChapter3Route:
      StudyCornerComputerBasicsChapter3Route,
    StudyCornerComputerBasicsChapter4Route:
      StudyCornerComputerBasicsChapter4Route,
    StudyCornerComputerBasicsChapter5Route:
      StudyCornerComputerBasicsChapter5Route,
    StudyCornerComputerBasicsExcelBasicKnowledgeRoute:
      StudyCornerComputerBasicsExcelBasicKnowledgeRoute,
    StudyCornerComputerBasicsWordBasicKnowledgeRoute:
      StudyCornerComputerBasicsWordBasicKnowledgeRoute,
    StudyCornerComputerBasicsIndexRoute: StudyCornerComputerBasicsIndexRoute,
  }

const StudyCornerComputerBasicsRouteWithChildren =
  StudyCornerComputerBasicsRoute._addFileChildren(
    StudyCornerComputerBasicsRouteChildren,
  )

interface StudyCornerGeneralAwarenessRouteChildren {
  StudyCornerGeneralAwarenessChapter1Route: typeof StudyCornerGeneralAwarenessChapter1Route
  StudyCornerGeneralAwarenessChapter2Route: typeof StudyCornerGeneralAwarenessChapter2Route
  StudyCornerGeneralAwarenessChapter3Route: typeof StudyCornerGeneralAwarenessChapter3Route
  StudyCornerGeneralAwarenessChapter4Route: typeof StudyCornerGeneralAwarenessChapter4Route
  StudyCornerGeneralAwarenessChapter5Route: typeof StudyCornerGeneralAwarenessChapter5Route
  StudyCornerGeneralAwarenessChapter6Route: typeof StudyCornerGeneralAwarenessChapter6Route
  StudyCornerGeneralAwarenessIndexRoute: typeof StudyCornerGeneralAwarenessIndexRoute
}

const StudyCornerGeneralAwarenessRouteChildren: StudyCornerGeneralAwarenessRouteChildren =
  {
    StudyCornerGeneralAwarenessChapter1Route:
      StudyCornerGeneralAwarenessChapter1Route,
    StudyCornerGeneralAwarenessChapter2Route:
      StudyCornerGeneralAwarenessChapter2Route,
    StudyCornerGeneralAwarenessChapter3Route:
      StudyCornerGeneralAwarenessChapter3Route,
    StudyCornerGeneralAwarenessChapter4Route:
      StudyCornerGeneralAwarenessChapter4Route,
    StudyCornerGeneralAwarenessChapter5Route:
      StudyCornerGeneralAwarenessChapter5Route,
    StudyCornerGeneralAwarenessChapter6Route:
      StudyCornerGeneralAwarenessChapter6Route,
    StudyCornerGeneralAwarenessIndexRoute:
      StudyCornerGeneralAwarenessIndexRoute,
  }

const StudyCornerGeneralAwarenessRouteWithChildren =
  StudyCornerGeneralAwarenessRoute._addFileChildren(
    StudyCornerGeneralAwarenessRouteChildren,
  )

interface StudyCornerRouteChildren {
  StudyCornerComputerBasicsRoute: typeof StudyCornerComputerBasicsRouteWithChildren
  StudyCornerGeneralAwarenessRoute: typeof StudyCornerGeneralAwarenessRouteWithChildren
  StudyCornerQuizResultRoute: typeof StudyCornerQuizResultRoute
  StudyCornerIndexRoute: typeof StudyCornerIndexRoute
}

const StudyCornerRouteChildren: StudyCornerRouteChildren = {
  StudyCornerComputerBasicsRoute: StudyCornerComputerBasicsRouteWithChildren,
  StudyCornerGeneralAwarenessRoute:
    StudyCornerGeneralAwarenessRouteWithChildren,
  StudyCornerQuizResultRoute: StudyCornerQuizResultRoute,
  StudyCornerIndexRoute: StudyCornerIndexRoute,
}

const StudyCornerRouteWithChildren = StudyCornerRoute._addFileChildren(
  StudyCornerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  CertificateRoute: CertificateRoute,
  ContactRoute: ContactRoute,
  DisclaimerRoute: DisclaimerRoute,
  EnglishRoute: EnglishRouteWithChildren,
  HindiRoute: HindiRouteWithChildren,
  LoginRoute: LoginRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ProgressRoute: ProgressRoute,
  ResultRoute: ResultRoute,
  StudyCornerRoute: StudyCornerRouteWithChildren,
  TermsRoute: TermsRoute,
  TestRoute: TestRoute,
  TypingStartGuideRoute: TypingStartGuideRoute,
  TypingTipsRoute: TypingTipsRoute,
  UpcomingExamsRoute: UpcomingExamsRoute,
  WordLearningRoute: WordLearningRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
